# Generated by Django 6.0.4 on 2026-05-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('farmer_name', models.CharField(max_length=100)),
                ('mobile_num', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('paddy_variety', models.CharField(max_length=100)),
                ('moisture', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_moisture_measured', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
