# Generated by Django 6.0.4 on 2026-05-07 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovtPaddyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Government Rate')),
                ('paddy_variety', models.CharField(max_length=100, verbose_name='Paddy Variety')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=100, verbose_name='Vehicle Number')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Driver Name')),
                ('driver_contact', models.CharField(max_length=100, verbose_name='Driver Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Worker Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerTicket',
            fields=[
                ('priority', models.AutoField(primary_key=True, serialize=False, verbose_name='Priority')),
                ('tracking_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Tracking ID')),
                ('farmer_name', models.CharField(max_length=100, verbose_name='Farmer Name')),
                ('mobile_num', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('aadhar_num', models.CharField(max_length=12, verbose_name='Aadhar Number')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('moisture', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Moisture')),
                ('date_moisture_measured', models.DateField(verbose_name='Date Moisture Measured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Ticket Booked', 'Ticket Booked'), ('Ongoing', 'Ongoing'), ('Packed', 'Packed'), ('Picked', 'Picked'), ('Transported', 'Transported')], default='Ticket Booked', max_length=100, verbose_name='Status')),
                ('paddy_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.govtpaddyrate', verbose_name='Paddy Variety')),
            ],
        ),
        migrations.CreateModel(
            name='WorkersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to='farmers.workers', verbose_name='Group Leader')),
                ('group_members', models.ManyToManyField(blank=True, related_name='member_of_groups', to='farmers.workers', verbose_name='Group Members')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerConsignmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bags', models.IntegerField(verbose_name='Number of bags (40 kg)')),
                ('brokerage_per_bag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Brokerage per bag (75 kg)')),
                ('total_brokerage', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total Brokerage (calculated)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consignment_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Consignment Created By')),
                ('tracking_id', models.OneToOneField(limit_choices_to={'status': 'Packed'}, on_delete=django.db.models.deletion.CASCADE, to='farmers.farmerticket')),
                ('vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.vehicleinfo', verbose_name='Vehicle')),
                ('workers_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.workersgroup', verbose_name='Workers Group')),
            ],
        ),
    ]
