# Generated by Django 6.0.4 on 2026-05-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerTicket',
            fields=[
                ('priority', models.AutoField(primary_key=True, serialize=False, verbose_name='Priority')),
                ('tracking_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Tracking ID')),
                ('farmer_name', models.CharField(max_length=100, verbose_name='Farmer Name')),
                ('mobile_num', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('aadhar_num', models.CharField(max_length=12, verbose_name='Aadhar Number')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('paddy_variety', models.CharField(max_length=100, verbose_name='Paddy Variety')),
                ('moisture', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Moisture')),
                ('date_moisture_measured', models.DateField(verbose_name='Date Moisture Measured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Ticket Booked', 'Ticket Booked'), ('Ongoing', 'Ongoing'), ('Packed', 'Packed'), ('Picked', 'Picked'), ('Transported', 'Transported')], default='Ticket Booked', max_length=100, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerConsignmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bags', models.IntegerField()),
                ('govt_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brokerage_per_bag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tracking_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmerticket')),
            ],
        ),
    ]
